fix(server): Rename confusing flag `replica_reconnect_on_master_restart`
That was a misleading name, as the logic was the exact opposite (oops :))

This PR introduces a new name for the same flag: `break_replication_on_master_restart`

Instead of removing the old one, we're using `ABSL_RETIRED_FLAG` API to
keep that flag in the flag parsing logic, while ignoring its value.

When using the retired flag, users will see a warning message (which
will not affect the server otherwise:

```shell
$ ./dragonfly --dbfilename= --logtostdout --replica_reconnect_on_master_restart
ERROR: Accessing retired flag 'replica_reconnect_on_master_restart'
```